"alpine weather statistics": "Day"
"evaporation": "Day"
"humidity": "Day"
"lightning": "Day"
"luminance": "Day"
"phenology": "Day"
"pollen data": "Day"
"precipitation": "Day"
"pressure": "Day"
"radiation": "Day"
"sensor-supported weather observation": "Day"
"snow": "Day"
"soil temperature": "Day"
"sunshine": "Day"
"technical standards": "Day"
"technical values": "Day"
"temperature": "Day"
"visual observation": "Day"
"wind": "Day"