"D":
  - "alpine weather statistics"
  - "evaporation"
  - "humidity"
  - "lightning"
  - "luminance"
  - "phenology"
  - "pollen data"
  - "precipitation"
  - "pressure"
  - "radiation"
  - "sensor-supported weather observation"
  - "snow"
  - "soil temperature"
  - "sunshine"
  - "technical standards"
  - "technical values"
  - "temperature"
  - "visual observation"
"M":
  - "wind"
